sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 414432

  redis:
    host: localhost
    port: 6379
    password: 414432
    database: 0

  wechat:
    appid: wx4ec690b5aee0178b
    secret: 6339b2854c06ba6809ba2e3f0dec9442